"use client";
import Link from "next/link"; import { Search, UserRoundCog } from "lucide-react"; import { useEffect, useMemo, useState } from "react";
type User = { userId: string; email: string; role: string; status: string; credits: number; createdAt: string; verifiedAt?: string };
export function AdminClient() {
  const [users, setUsers] = useState<User[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/admin/users"); const body = await response.json(); if (response.ok) setUsers(body.data); setLoading(false); }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => users.filter((user) => user.email.toLowerCase().includes(query.toLowerCase())), [users, query]);
  async function toggle(user: User) { const status = user.status === "suspended" ? "active" : "suspended"; if (status === "suspended" && !confirm("Suspend this user and revoke all active keys?")) return; const response = await fetch(`/api/admin/users/${user.userId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (response.ok) await load(); }
  async function credit(user: User) { const amount = Number(prompt("Credit adjustment (use negative to deduct)", "10")); if (!Number.isSafeInteger(amount) || amount === 0) return; const reason = prompt("Reason", "Support adjustment") || "Support adjustment"; const response = await fetch(`/api/admin/users/${user.userId}/credits`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ amount, reason }) }); setMessage(response.ok ? `${amount} credit adjustment applied to ${user.email}.` : "Adjustment failed."); if (response.ok) await load(); }
  return <main className="portal-shell"><header className="portal-header"><Link href="/">Logo Market Place</Link><nav><Link href="/dashboard">Dashboard</Link><Link href="/pricing">Pricing</Link></nav></header><div className="portal-wrap"><div className="portal-intro"><div><p>ADMINISTRATION</p><h1>Customer operations</h1><span>Balances, access state, and manual adjustments.</span></div></div>{message && <p className="form-status form-success">{message}</p>}
    <section className="portal-panel"><div className="panel-heading"><div><p>ACCOUNTS</p><h2>{users.length} customers</h2></div><label className="admin-search"><Search /><span className="sr-only">Search users</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by email" /></label></div>
      {loading ? <p className="empty-ledger">Loading accounts...</p> : <div className="admin-table"><div className="admin-row admin-head"><span>Customer</span><span>Status</span><span>Credits</span><span>Joined</span><span>Actions</span></div>{filtered.map((user) => <div className="admin-row" key={user.userId}><div><UserRoundCog /><span><strong>{user.email}</strong><small>{user.role}{user.verifiedAt ? " · Verified" : " · Pending verification"}</small></span></div><span className={`status-pill status-pill--${user.status}`}>{user.status}</span><b>{user.credits.toLocaleString()}</b><span>{new Date(user.createdAt).toLocaleDateString()}</span><div><button onClick={() => credit(user)}>Adjust credits</button><button className="text-danger" onClick={() => toggle(user)}>{user.status === "suspended" ? "Reactivate" : "Suspend"}</button></div></div>)}</div>}
    </section></div></main>;
}
