"use client";
import Link from "next/link"; import { Copy, KeyRound, LogOut, Plus, Trash2, WalletCards } from "lucide-react"; import { useState } from "react";
type KeyItem = { keyId: string; name: string; prefix: string; last4: string; status: string; createdAt: string; lastUsedAt?: string };
type Entry = { id: string; type: string; amount: number; balanceAfter: number; description: string; createdAt: string };
export function DashboardClient({ email, role, initialCredits, initialKeys, initialLedger }: { email: string; role: string; initialCredits: number; initialKeys: KeyItem[]; initialLedger: Entry[] }) {
  const [keys, setKeys] = useState(initialKeys); const [secret, setSecret] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function createKey() { const name = window.prompt("Name this key", "Production"); if (!name) return; setBusy(true); setError(""); const response = await fetch("/api/account/keys", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const body = await response.json(); setBusy(false); if (!response.ok) { setError(body.error?.message); return; } setSecret(body.data.secret); setKeys((current) => [body.data, ...current]); }
  async function revoke(keyId: string) { if (!window.confirm("Revoke this API key? Existing integrations will stop working.")) return; const response = await fetch(`/api/account/keys/${keyId}`, { method: "DELETE" }); if (response.ok) setKeys((current) => current.map((key) => key.keyId === keyId ? { ...key, status: "revoked" } : key)); }
  async function signout() { await fetch("/api/account/signout", { method: "POST" }); window.location.href = "/"; }
  return <main className="portal-shell"><header className="portal-header"><Link href="/">Logo Market Place</Link><nav><Link href="/developers">Docs</Link><Link href="/pricing">Pricing</Link>{role === "admin" && <Link href="/admin">Admin</Link>}<button onClick={signout}><LogOut />Sign out</button></nav></header>
    <div className="portal-wrap"><div className="portal-intro"><div><p>ACCOUNT</p><h1>Developer dashboard</h1><span>{email}</span></div><Link className="buy-link" href="/pricing"><WalletCards />Buy credits</Link></div>
      <section className="metric-grid"><article><span>Available credits</span><strong>{initialCredits.toLocaleString()}</strong><small>1 credit = 1 valid API request</small></article><article><span>Active keys</span><strong>{keys.filter((key) => key.status === "active").length}<em>/ 3</em></strong><small>Named and independently revocable</small></article><article><span>Credit expiry</span><strong>Never</strong><small>Purchased credits remain available</small></article></section>
      {secret && <aside className="secret-banner" role="status"><div><strong>Copy your new API key now</strong><p>It will not be shown again.</p><code>{secret}</code></div><button onClick={() => navigator.clipboard.writeText(secret)}><Copy />Copy</button><button aria-label="Dismiss key" onClick={() => setSecret("")}>Done</button></aside>}
      <section className="portal-panel"><div className="panel-heading"><div><p>API KEYS</p><h2>Credentials</h2></div><button className="primary-button" onClick={createKey} disabled={busy || keys.filter((k) => k.status === "active").length >= 3}><Plus />Create key</button></div>{error && <p className="form-status form-error">{error}</p>}
        <div className="key-list">{keys.length ? keys.map((key) => <article key={key.keyId}><KeyRound /><div><strong>{key.name}</strong><code>{key.prefix}...{key.last4}</code><small>Created {new Date(key.createdAt).toLocaleDateString()}{key.lastUsedAt ? ` · Last used ${new Date(key.lastUsedAt).toLocaleDateString()}` : " · Never used"}</small></div><span className={`status-pill status-pill--${key.status}`}>{key.status}</span>{key.status === "active" && <button className="icon-danger" aria-label={`Revoke ${key.name}`} onClick={() => revoke(key.keyId)}><Trash2 /></button>}</article>) : <div className="empty-state"><KeyRound /><strong>No API keys yet</strong><p>Create a key to make your first request.</p></div>}</div>
      </section>
      <section className="portal-panel"><div className="panel-heading"><div><p>LEDGER</p><h2>Credit activity</h2></div></div><div className="ledger-table"><div className="ledger-row ledger-head"><span>Description</span><span>Date</span><span>Change</span><span>Balance</span></div>{initialLedger.map((entry) => <div className="ledger-row" key={`${entry.id}-${entry.createdAt}`}><strong>{entry.description}</strong><span>{new Date(entry.createdAt).toLocaleString()}</span><b className={entry.amount > 0 ? "positive" : "negative"}>{entry.amount > 0 ? "+" : ""}{entry.amount}</b><span>{entry.balanceAfter}</span></div>)}{!initialLedger.length && <p className="empty-ledger">No credit activity yet.</p>}</div></section>
    </div></main>;
}
